spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: /Users/egorbatik/workspace-digitalhouse-clase-10-taller-de-coding/configuration-service/config-git
          default-label: master
server:
  port: 8888
